GET https://jvr2dcliw4.execute-api.sa-east-1.amazonaws.com/prod/spaces
###

GET https://jvr2dcliw4.execute-api.sa-east-1.amazonaws.com/prod/spaces?id=6edcf239-9b59-4acc-a128-3028b6f0a2dc
###

POST https://jvr2dcliw4.execute-api.sa-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
  "location": "Buenos Aires"
}
###

PUT https://jvr2dcliw4.execute-api.sa-east-1.amazonaws.com/prod/spaces?id=6b07dd34-1e8a-4f23-ba50-1f34dab881f9
Content-Type: application/json

{
  "location": "Amsterdam"

}
###

DELETE https://jvr2dcliw4.execute-api.sa-east-1.amazonaws.com/prod/spaces?id=6b07dd34-1e8a-4f23-ba50-1f34dab881f9
###